### PR TITLE
Premium sponsors page sc

### PR DESCRIPTION
**Pull request by yarivShamash**

### CODE REVIEW

**Comment by yarivShamash** [comment]
Hey Serge,

I had two unsolved issues:
1. I noticed that only `Open Positions` segment has a symbol on the heading.
2. I'm not sure if it's the compiling issue we encountered or something else but I noticed that when the screen width is under 480px the page alignment goes bad.

We'll keep in touch :)

**Comment by sergelerner** [comment]
VISUAL REVIEW

1. Compare Sponsor Page 

https://summit2019.reversim.com/sponsor/Redash

Screen Shot 2019-10-24 at 17 59 07

http://local.reversim.com:3000/sponsor/Redash

Screen Shot 2019-10-24 at 18 00 07

Something is off here

2. The button text in SponsorItem is not aligned in the center

https://summit2019.reversim.com/sponsors.html

Screen Shot 2019-10-24 at 18 03 28

http://local.reversim.com:3000/sponsors

Screen Shot 2019-10-24 at 18 03 23

3. Our Technology Story **Tags**

https://summit2019.reversim.com/sponsor/Redash

Screen Shot 2019-10-24 at 18 06 34

http://local.reversim.com:3000/sponsor/Redash

Screen Shot 2019-10-24 at 18 06 59

4. Sponsor Page on small screen

https://summit2019.reversim.com/sponsor/Redash

Screen Shot 2019-10-24 at 18 07 55

http://local.reversim.com:3000/sponsor/Redash

Screen Shot 2019-10-24 at 18 08 46

5. Some links inside a paragraph lost their style and functionality

https://summit2019.reversim.com/sponsor/Redash

Screen Shot 2019-10-24 at 18 09 44

http://local.reversim.com:3000/sponsor/Redash

Screen Shot 2019-10-24 at 18 10 43

6. The padding between some blocks is different

https://summit2019.reversim.com/sponsor/Redash

Screen Shot 2019-10-24 at 18 12 15

http://local.reversim.com:3000/sponsor/Redash

Screen Shot 2019-10-24 at 18 12 32

7. The footer is quiet different (font, space between icons etc) both in large and small size

https://summit2019.reversim.com/sponsor/Redash

Screen Shot 2019-10-24 at 18 13 48

http://local.reversim.com:3000/sponsor/Redash

Screen Shot 2019-10-24 at 18 14 34

https://summit2019.reversim.com/sponsor/Redash

Screen Shot 2019-10-24 at 18 14 57

http://local.reversim.com:3000/sponsor/Redash

Screen Shot 2019-10-24 at 18 15 28

**Comment by sergelerner** [comment]
More visual review

Screen Shot 2019-10-31 at 16 12 45

About
Tech-Story
Reversim & Us

Are far Apart

**Comment by sergelerner** [comment]
Screen Shot 2019-10-31 at 16 15 13

the tags style broke

**Comment by sergelerner** [comment]
Screen Shot 2019-10-31 at 16 16 05

Mobile

**Comment by sergelerner** [comment]
☝️ this branch has conflicts

**Comment by sergelerner** [comment]
========================================================================================================================================================================================================================
👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇👇

__________________________________________NEW VISUAL REVIEW________________________________________

**Comment by sergelerner** [comment]
Production
Reversim_Summit_2019

Localhost
Sponsors_·_Reversim_Summit_2019

**Comment by sergelerner** [comment]
Production 
Reversim_Summit_2019

Localhost
Redash_·_Reversim_Summit_2019

~100 pixel less in width 

lets make sure content width is a variable shared among pages

**Comment by sergelerner** [comment]
Production
Reversim_Summit_2019

Localhost 
Redash_·_Reversim_Summit_2019

**Comment by sergelerner** [comment]
Production
Reversim_Summit_2019

Localhost
Redash_·_Reversim_Summit_2019

**Comment by sergelerner** [comment]
Production
Reversim_Summit_2019

Localhost

Redash_·_Reversim_Summit_2019

Redash_·_Reversim_Summit_2019 2

Redash_·_Reversim_Summit_2019 3

**Comment by sergelerner** [comment]
Localhost
Redash_·_Reversim_Summit_2019 4

**Pull request merged**
