### PR TITLE
Cfp form touchups

### PR DESCRIPTION
**Pull request by yarivShamash**

### CODE REVIEW

**Comment by sergelerner** [comment]
Visual Review
==================

1. When clicking "Submit a New Proposal" button, it goes to the new page and there is a quick flicker of this screen

Screen Shot 2020-02-11 at 15 37 17

only later I see this screen 

Screen Shot 2020-02-11 at 15 39 10

in the screen above I suggest to center all the text to the center

**Comment by sergelerner** [comment]
2. Not sure its related to this PR, but when I go to edit my proposal there is an error and I get a white page

so clicking here:

sss_·_Reversim_Summit_2019

leads here:

Reversim_Summit_2019

**Comment by sergelerner** [comment]
3. Text color

Call_for_papers_·_Reversim_Summit_2019

**Comment by sergelerner** [comment]
4. Small stuff I noticed

Call_for_papers_·_Reversim_Summit_2019

**Comment by sergelerner** [comment]
5. Readability

Ok, so you made it much more readable! But there is some place for improvement IMO. Have a look at website like Medium, look at the width of the text and the font sizes. For inspiration. 

Here how it looks today

Call_for_papers_·_Reversim_Summit_2019

I played a little, and here how it can look

Call_for_papers_·_Reversim_Summit_2019 2

I made all sort of changes, but the key takeaways
1. The width of the block text (also called "the measure" in _typography_) should be smaller I gave a max-width of 760, its not easy for the human eye to read wide text. Wikipedia is a bad bad example of how text should look.

2. The text should be larger, something like 21px, and thin. 

3. The titles can be smaller 36px, now they are very big, when you make them smaller make them also bold, it will compensate the size reduction.

4. Te block of text should be continues. Meaning after the dot there should be no new line. If there is a new line it should look like a paragraph with some margin at the bottom. Since we have many `<p>` tags and they are block level elements in css they create a new line. I hacked , without changing the html, by giving it `display: inline; margin-right: 20px;`

5. Look at Medium for inspiration, and notice how it is more comfortable to read

**Comment by yarivShamash** [comment]
good read about typography and "the measure" etc.[https://material.io/design/typography/understanding-typography.html#readability](url)

**Pull request merged**
